name: AWS S3 deploy

on:
  push:
    branches:
      - deploy

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -name: Checkout source code.
       uses: actions/checkout@v3

      -name: Install dependencies
       run: npm ci
      
      -name: Build
       run: npm run build